### ISSUE TITLE
Fatal error: Error - you must call Sign.configure(_:) before accessing the shared instance.

### ISSUE THREAD

**Issue by chocoford** [WalletConnect/web3modal-swift#58]
**Describe the bug**
App crashs due to `Fatal error: Error - you must call Sign.configure(_:) before accessing the shared instance.` after calling `Web3Modal.configure(...)`

**SDK Version**
 - Client: Swift
 - Version 1.3.0

This is because the dependency - [WalletConnectSwiftV2](https://github.com/WalletConnect/WalletConnectSwiftV2) update to `1.13.0`

**Comment by kiarashvosough1999** [comment]
I am wondering whether they test SDK before publishing or not!! This Bug is the Art of using Singleton everywhere....

**Comment by chichkanov** [comment]
@radeknovis @llbartekll @TalhaAli00  could you please guys look into this issue? The library crashes an app on start due to this

**Comment by llbartekll** [comment]
Do you properly configure Sign client? Example App doesn't crash.

**Comment by llbartekll** [comment]
could you guys upgrade to 1.3.1?

**Comment by llbartekll** [comment]
it's been confirmed that the issue is fixed: https://github.com/WalletConnect/web3modal-swift/issues/51#issuecomment-1999274200

**Comment by chocoford** [comment]
After upgrading to 1.3.1, the problem still exists. Did I miss something with the configuration of `Web3Model`?

**Comment by llbartekll** [comment]
> Does my app needs to call the Sign.configure(_:) function?

1.3.1 doesn't, try to resolve package dependencies again
